server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=utf8
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  spring:
    datasource:
      initialization-mode: always

  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

h2:
  console:
    enabled: true

microservice:
  address:
    url: "http://localhost:8081/casas"
